### ISSUE TITLE
Error when using  min_patch_size=4

### ISSUE THREAD

**Issue by Walid-Ahmed** [TomerRonen34/mixed-resolution-vit#5]
Hi, thanks for this great work.

I am trying to use the following parameters for Tokenization :
image_size = 224
min_patch_size = 4
max_patch_size = 8 
quadtree_num_patches = 2002

I am getting the following error when using FeatureBasedPatchScorer:
/examples/mixed_res/patch_scorers/patch_scorer.py", line 82, in _calculate_scores
    raise ValueError(
ValueError: map_size (7) < grid_size (28)

If I use RandomPatchScorer(), it works fine
Can you please help me understand and reslove this error?

Thanks in advance

**Comment by TomerRonen34** [comment]
This error is due to the patch scorer features being a factor of x32
smaller than the image, while you require them to be x8 smaller than the
image in order to rank patches of size 8x8 pixels. You can try taking a
shallower level of the CNN inside the FeatureBased patch scorer (after 3
downsamples instead of after 5 downsamples which is the default). Another
option is to use the PixelBlur patch scorer without any code changes,
although I only recommend it for playground testing, as it's far less
semantically strong than the FeatureBased scorer.

**Comment by Walid-Ahmed** [comment]
Thanks a lot
I followed your advice and code is working now

**Comment by TomerRonen34** [comment]
That's great to hear :)
I hope it works well
